-- TABELA PRODUTO
CREATE TABLE HPRODUTO (
    HPRD_ID   NUMERIC(6,0),
    HPRD_NOME VARCHAR2(100),
    HPRD_DATE TIMESTAMP
);
/
-- TABELA CANAL
CREATE TABLE HCANAL (
    HCAN_ID   NUMERIC(6,0),
    HCAN_NOME VARCHAR2(50),
    HCAN_DATE TIMESTAMP
);
/
-- TABELA LOJA
CREATE TABLE HLOJA (
    HLOJ_ID   NUMERIC(6,0),
    HLOJ_NOME VARCHAR2(50),
    HLOJ_DATE TIMESTAMP
);
/
-- TABELA SKU
CREATE TABLE HSKU (
    HSKU_ID     NUMERIC(6,0),
    HSKU_KEY    VARCHAR2(50),
    HSKU_PRD_ID NUMERIC(6,0),
    HSKU_CUSTO  NUMERIC(12,2),
    HSKU_DATE   TIMESTAMP
);
/
-- TABELA VENDA
CREATE TABLE HVENDA (
    HVND_ID          NUMERIC(6,0),
    HVND_PEDIDO      VARCHAR2(100),
    HVND_LOJ_ID      NUMERIC(6,0),
    HVND_CAN_ID      NUMERIC(6,0),
    HVND_DATA_VENDA  DATE,
    HVND_VALOR_TOTAL NUMERIC(12,2),
    HVND_DATE        TIMESTAMP
);
/
-- TABELA ITEM_VENDA
CREATE TABLE HITEM_VENDA (
    HITVND_VND_ID NUMERIC(6,0),
    HITVND_SKU_ID NUMERIC(6,0),
    HITVND_QTDE   NUMBER(6,0),
    HITVND_CUSTO  NUMERIC(12,2),
    HITVND_VALOR  NUMERIC(12,2),
    HITVND_DATE   TIMESTAMP
);
/
COMMIT;