
-- PRODUTO
COMMENT ON TABLE  HPRODUTO          IS 'TABELA REFERENTE AO HISTORICO DA TABELA PRODUTO';
COMMENT ON COLUMN HPRODUTO.HPRD_ID   IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA DA TABELA PRODUTO';
COMMENT ON COLUMN HPRODUTO.HPRD_NOME IS 'COLUNA REFERENTE AO REGISTRO DO NOME DO PRODUTO';

-- CANAL
COMMENT ON TABLE  HCANAL          IS 'TABELA REFERENTE AO HISTORICO DA TABELA CANAL';
COMMENT ON COLUMN HCANAL.HCAN_ID   IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA DA TABELA CANAL';
COMMENT ON COLUMN HCANAL.HCAN_NOME IS 'COLUNA REFERENTE AO REGISTRO DO NOME DO CANAL';

-- LOJA
COMMENT ON TABLE  HLOJA          IS 'TABELA REFERENTE AO HISTORICO DA TABELA LOJA';
COMMENT ON COLUMN HLOJA.HLOJ_ID   IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA DA TABELA LOJA';
COMMENT ON COLUMN HLOJA.HLOJ_NOME IS 'COLUNA REFERENTE AO REGISTRO DO NOME DA LOJA';

-- SKU
COMMENT ON TABLE  HSKU            IS 'TABELA REFERENTE AO HISTORICO DA TABELA SKU';
COMMENT ON COLUMN HSKU.HSKU_ID     IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA DA TABELA SKU';
COMMENT ON COLUMN HSKU.HSKU_KEY    IS 'COLUNA REFERENTE AO REGISTRO DO CODIGO DE IDENTIFICACAO UNICA DO PRODUTO';
COMMENT ON COLUMN HSKU.HSKU_PRD_ID IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA PRODUTO';
COMMENT ON COLUMN HSKU.HSKU_CUSTO  IS 'COLUNA REFERENTE AO REGISTRO DO CUSTO DO SKU';

-- VENDA
COMMENT ON TABLE  HVENDA                 IS 'TABELA REFERENTE AO HISTORICO DA TABELA VENDA';
COMMENT ON COLUMN HVENDA.HVND_ID          IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA DA TABELA VENDA';
COMMENT ON COLUMN HVENDA.HVND_PEDIDO      IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE DE IDENTIFICACAO GERADA PELO MARKETPLACE';
COMMENT ON COLUMN HVENDA.HVND_LOJ_ID      IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA LOJA';
COMMENT ON COLUMN HVENDA.HVND_CAN_ID      IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA CANAL';
COMMENT ON COLUMN HVENDA.HVND_DATA_VENDA  IS 'COLUNA REFERENTE AO REGISTRO DA DATA EM QUE FOI REALIZADA A VENDA';
COMMENT ON COLUMN HVENDA.HVND_VALOR_TOTAL IS 'COLUNA REFERENTE AO REGISTRO DO VALOR TOTAL DA VENDA';

-- ITEM_VENDA
COMMENT ON TABLE  HITEM_VENDA              IS 'TABELA REFERENTE AO HISTORICO DA TABELA ITENS PRESENTES NAS VENDAS';
COMMENT ON COLUMN HITEM_VENDA.HITVND_VND_ID IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA COMPOSTA E ESTRANGEIRA REFERENCIADA PELA TABELA VENDAS';
COMMENT ON COLUMN HITEM_VENDA.HITVND_SKU_ID IS 'COLUNA REFERENTE AO REGISTRO DA CHAVE PRIMARIA COMPOSTA E ESTRANGEIRA REFERENCIADA PELA TABELA SKU';
COMMENT ON COLUMN HITEM_VENDA.HITVND_QTDE   IS 'COLUNA REFERENTE AO REGISTRO DA QUANTIDADE DE ITENS';
COMMENT ON COLUMN HITEM_VENDA.HITVND_CUSTO  IS 'CUSTO REFERENTE AO REGISTRO DO PRODUTO NO MOMENTO DA VENDA';
COMMENT ON COLUMN HITEM_VENDA.HITVND_VALOR  IS 'COLUNA REFERENTE AO REGISTRDO DO VALOR TOTAL DOS ITENS';

/
COMMIT;






















