-- PKS PRODUTO
ALTER TABLE HPRODUTO
    ADD CONSTRAINT PK_HPRD PRIMARY KEY (HPRD_ID, HPRD_DATE);

-- PKS CANAL
ALTER TABLE HCANAL
    ADD CONSTRAINT PK_HCAN PRIMARY KEY (HCAN_ID, HCAN_DATE);

-- PKS LOJA
ALTER TABLE HLOJA
    ADD CONSTRAINT PK_HLOJ PRIMARY KEY (HLOJ_ID, HLOJ_DATE);

-- PKS SKU
ALTER TABLE HSKU
    ADD CONSTRAINT PK_HSKU PRIMARY KEY (HSKU_ID, HSKU_DATE);

-- PKS VENDA
ALTER TABLE HVENDA
    ADD CONSTRAINT PK_HVND PRIMARY KEY (HVND_ID, HVND_DATE);

-- PKS ITEM VENDA
ALTER TABLE HITEM_VENDA
    ADD CONSTRAINT PK_HITVND PRIMARY KEY (HITVND_VND_ID, HITVND_SKU_ID, HITVND_DATE);

/
COMMIT;
