-- TRIGGER PRODUTO
CREATE TRIGGER TG_HPRD
BEFORE UPDATE OR DELETE ON PRODUTO
FOR EACH ROW
BEGIN
    INSERT INTO 
        HPRODUTO
    VALUES(
        :OLD.PRD_ID,
        :OLD.PRD_NOME,
        SYSDATE
    );
END;
/

-- TRIGGER CANAL
CREATE TRIGGER TG_HCAN
BEFORE UPDATE OR DELETE ON CANAL
FOR EACH ROW
BEGIN
    INSERT INTO 
        HCANAL
    VALUES(
        :OLD.CAN_ID,
        :OLD.CAN_NOME,
        SYSDATE
    );
END;
/

-- TRIGGER LOJA
CREATE TRIGGER TG_HLOJ
BEFORE UPDATE OR DELETE ON LOJA
FOR EACH ROW
BEGIN
    INSERT INTO 
        HLOJA
    VALUES(
        :OLD.LOJ_ID,
        :OLD.LOJ_NOME,
        SYSDATE
    );
END;
/

-- TRIGGER SKU
CREATE TRIGGER TG_HSKU
BEFORE UPDATE OR DELETE ON SKU
FOR EACH ROW
BEGIN
    INSERT INTO 
        HSKU
    VALUES(
        :OLD.SKU_ID,
        :OLD.SKU_KEY,
        :OLD.SKU_PRD_ID,
        :OLD.SKU_CUSTO,
        SYSDATE
    );
END;
/

-- TRIGGER VENDA
CREATE TRIGGER TG_HVND
BEFORE UPDATE OR DELETE ON VENDA
FOR EACH ROW
BEGIN
    INSERT INTO 
        HVENDA
    VALUES(
        :OLD.VND_ID,
        :OLD.VND_PEDIDO,
        :OLD.VND_LOJ_ID,
        :OLD.VND_CAN_ID,
        :OLD.VND_DATA_VENDA,
        :OLD.VND_VALOR_TOTAL,
        SYSDATE
    );
END;
/

-- TRIGGER ITEM_VENDA
CREATE TRIGGER TG_HITVND
BEFORE UPDATE OR DELETE ON ITEM_VENDA
FOR EACH ROW
BEGIN
    INSERT INTO 
        HITEM_VENDA
    VALUES(
        :OLD.ITVND_VND_ID,
        :OLD.ITVND_SKU_ID,
        :OLD.ITVND_QTDE,
        :OLD.ITVND_CUSTO,
        :OLD.ITVND_VALOR,
        SYSDATE
    );
END;
/

COMMIT;