-- TABELA PRODUTO
CREATE TABLE PRODUTO (
    PRD_ID   NUMERIC(6,0),
    PRD_NOME VARCHAR2(100) CONSTRAINT CK_PRD_NN_01 NOT NULL
);
/

-- TABELA CANAL
CREATE TABLE CANAL (
    CAN_ID   NUMERIC(6,0),
    CAN_NOME VARCHAR2(50) CONSTRAINT CK_CAN_NN_01 NOT NULL
);
/

-- TABELA LOJA
CREATE TABLE LOJA (
    LOJ_ID   NUMERIC(6,0),
    LOJ_NOME VARCHAR2(50) CONSTRAINT CK_LOJ_NN_01 NOT NULL
);
/

-- TABELA SKU
CREATE TABLE SKU (
    SKU_ID     NUMERIC(6,0),
    SKU_KEY    VARCHAR2(50)  CONSTRAINT UK_SKU_01    UNIQUE
                             CONSTRAINT CK_SKU_NN_01 NOT NULL,
    SKU_PRD_ID NUMERIC(6,0)  CONSTRAINT CK_SKU_NN_02 NOT NULL,
    SKU_CUSTO  NUMERIC(12,2) CONSTRAINT CK_SKU_NN_03 NOT NULL
);
/

-- TABELA VENDA
CREATE TABLE VENDA (
    VND_ID          NUMERIC(6,0),
    VND_PEDIDO      VARCHAR2(100)  CONSTRAINT UK_VND_01    UNIQUE
                                   CONSTRAINT CK_VND_NN_01 NOT NULL,
    VND_LOJ_ID      NUMERIC(6,0)   CONSTRAINT CK_VND_NN_02 NOT NULL,
    VND_CAN_ID      NUMERIC(6,0)   CONSTRAINT CK_VND_NN_03 NOT NULL,
    VND_DATA_VENDA  DATE           CONSTRAINT CK_VND_NN_04 NOT NULL,
    VND_VALOR_TOTAL NUMERIC(12,2)  CONSTRAINT CK_VND_NN_05 NOT NULL
);
/

-- TABELA ITEM_VENDA
CREATE TABLE ITEM_VENDA (
    ITVND_VND_ID NUMERIC(6,0)  CONSTRAINT CK_ITVND_NN_01 NOT NULL,
    ITVND_SKU_ID NUMERIC(6,0)  CONSTRAINT CK_ITVND_NN_02 NOT NULL,
    ITVND_QTDE   NUMBER(6,0)   CONSTRAINT CK_ITVND_NN_03 NOT NULL,
    ITVND_CUSTO  NUMERIC(12,2) CONSTRAINT CK_ITVND_NN_04 NOT NULL,
    ITVND_VALOR  NUMERIC(12,2) CONSTRAINT CK_ITVND_NN_05 NOT NULL
);
/

COMMIT;