
-- PRODUTO
COMMENT ON TABLE  PRODUTO          IS 'TABELA REFERENTE AOS PRODUTOS';
COMMENT ON COLUMN PRODUTO.PRD_ID   IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA PRODUTO';
COMMENT ON COLUMN PRODUTO.PRD_NOME IS 'COLUNA REFERENTE AO NOME DO PRODUTO';

-- CANAL
COMMENT ON TABLE  CANAL          IS 'TABELA REFERENTE AOS CANAIS DE VENDA';
COMMENT ON COLUMN CANAL.CAN_ID   IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA CANAL';
COMMENT ON COLUMN CANAL.CAN_NOME IS 'COLUNA REFERENTE AO NOME DO CANAL';

-- LOJA
COMMENT ON TABLE  LOJA          IS 'TABELA REFERENTE AS LOJAS';
COMMENT ON COLUMN LOJA.LOJ_ID   IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA LOJA';
COMMENT ON COLUMN LOJA.LOJ_NOME IS 'COLUNA REFERENTE AO NOME DA LOJA';

-- SKU
COMMENT ON TABLE  SKU            IS 'TABELA REFERENTE AOS SKUS';
COMMENT ON COLUMN SKU.SKU_ID     IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA SKU';
COMMENT ON COLUMN SKU.SKU_KEY    IS 'COLUNA REFERENTE AO CODIGO DE IDENTIFICACAO UNICA DO PRODUTO';
COMMENT ON COLUMN SKU.SKU_PRD_ID IS 'COLUNA REFERENTE A CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA PRODUTO';
COMMENT ON COLUMN SKU.SKU_CUSTO  IS 'COLUNA REFERENTE AO CUSTO DO SKU';

-- VENDA
COMMENT ON TABLE  VENDA                 IS 'TABELA REFERENTE AS VENDAS';
COMMENT ON COLUMN VENDA.VND_ID          IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA VENDA';
COMMENT ON COLUMN VENDA.VND_PEDIDO      IS 'COLUNA REFERENTE A CHAVE DE IDENTIFICACAO GERADA PELO MARKETPLACE';
COMMENT ON COLUMN VENDA.VND_LOJ_ID      IS 'COLUNA REFERENTE A CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA LOJA';
COMMENT ON COLUMN VENDA.VND_CAN_ID      IS 'COLUNA REFERENTE A CHAVE ESTRANGEIRA REFERENCIADA PELA TABELA CANAL';
COMMENT ON COLUMN VENDA.VND_DATA_VENDA  IS 'COLUNA REFERENTE A DATA EM QUE FOI REALIZADA A VENDA';
COMMENT ON COLUMN VENDA.VND_VALOR_TOTAL IS 'COLUNA REFERENTE AO VALOR TOTAL DA VENDA';

-- ITEM_VENDA
COMMENT ON TABLE  ITEM_VENDA              IS 'TABELA REFERENTE AOS ITENS PRESENTES NAS VENDAS';
COMMENT ON COLUMN ITEM_VENDA.ITVND_VND_ID IS 'COLUNA REFERENTE A CHAVE PRIMARIA COMPOSTA E ESTRANGEIRA REFERENCIADA PELA TABELA VENDAS';
COMMENT ON COLUMN ITEM_VENDA.ITVND_SKU_ID IS 'COLUNA REFERENTE A CHAVE PRIMARIA COMPOSTA E ESTRANGEIRA REFERENCIADA PELA TABELA SKU';
COMMENT ON COLUMN ITEM_VENDA.ITVND_QTDE   IS 'COLUNA REFERENTE A QUANTIDADE DE ITENS';
COMMENT ON COLUMN ITEM_VENDA.ITVND_CUSTO  IS 'CUSTO REFERENTE AO PRODUTO NO MOMENTO DA VENDA';
COMMENT ON COLUMN ITEM_VENDA.ITVND_VALOR  IS 'COLUNA REFERENTE AO VALOR TOTAL DOS ITENS';

/
COMMIT;






















