-- SEQUENCE PRODUTO
CREATE SEQUENCE SQ_PRD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SEQUENCE CANAL
CREATE SEQUENCE SQ_CAN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SEQUENCE LOJA
CREATE SEQUENCE SQ_LOJ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SEQUENCE SKU
CREATE SEQUENCE SQ_SKU
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SEQUENCE VENDA
CREATE SEQUENCE SQ_VND
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

/
COMMIT;