-- PKS PRODUTO
ALTER TABLE PRODUTO
    ADD CONSTRAINT PK_PRD PRIMARY KEY (PRD_ID);

-- PKS CANAL
ALTER TABLE CANAL
    ADD CONSTRAINT PK_CAN PRIMARY KEY (CAN_ID);

-- PKS LOJA
ALTER TABLE LOJA
    ADD CONSTRAINT PK_LOJ PRIMARY KEY (LOJ_ID);

-- PKS SKU
ALTER TABLE SKU
    ADD CONSTRAINT PK_SKU PRIMARY KEY (SKU_ID);

-- PKS VENDA
ALTER TABLE VENDA
    ADD CONSTRAINT PK_VND PRIMARY KEY (VND_ID);

-- PKS ITEM VENDA
ALTER TABLE ITEM_VENDA
    ADD CONSTRAINT PK_ITVND PRIMARY KEY (ITVND_VND_ID, ITVND_SKU_ID);

/
COMMIT;
