-- FKS SKU - PRODUTO
ALTER TABLE SKU
    ADD CONSTRAINT FK_SKU_PRD
    FOREIGN KEY (SKU_PRD_ID)
    REFERENCES PRODUTO (PRD_ID);

-- FKS VENDA - LOJA
ALTER TABLE VENDA
    ADD CONSTRAINT FK_VND_LOJ
    FOREIGN KEY (VND_LOJ_ID)
    REFERENCES LOJA (LOJ_ID);

-- FKS VENDA - CANAL
ALTER TABLE VENDA
    ADD CONSTRAINT FK_VND_CAN
    FOREIGN KEY (VND_CAN_ID)
    REFERENCES CANAL (CAN_ID);

-- FKS ITEM_VENDA - VENDA
ALTER TABLE ITEM_VENDA
    ADD CONSTRAINT FK_ITVND_VND
    FOREIGN KEY (ITVND_VND_ID)
    REFERENCES VENDA (VND_ID);

-- FKS ITEM_VENDA - SKU
ALTER TABLE ITEM_VENDA
    ADD CONSTRAINT FK_ITVND_SKU
    FOREIGN KEY (ITVND_SKU_ID)
    REFERENCES SKU (SKU_ID);

/
COMMIT;