-- TABELA AUDITORIA
CREATE TABLE AUDITORIA (
    AUD_ID           NUMERIC(6,0),
    AUD_TABELA       VARCHAR2(30),
    AUD_HIST_ID      VARCHAR2(100),
    AUD_COLUNA       VARCHAR2(30),
    AUD_VALOR_ANTIGO VARCHAR2(255),
    AUD_VALOR_NOVO   VARCHAR2(255),
    AUD_DATA         TIMESTAMP,
    AUD_USU_BD       VARCHAR2(30),
    AUD_USU_SO       VARCHAR2(255),
    AUD_OPERACAO     CHAR(1)
);
/
COMMIT;
