-- AUDITORIA
COMMENT ON TABLE  AUDITORIA                  IS 'TABELA REFERENTE A AUDITORIA DAS TABELAS DE HISTORICO';
COMMENT ON COLUMN AUDITORIA.AUD_ID           IS 'COLUNA REFERENTE A CHAVE PRIMARIA DA TABELA AUDITORIA';
COMMENT ON COLUMN AUDITORIA.AUD_TABELA       IS 'COLUNA REFERENTE AO NOME DA TABELA REGISTRADA';
COMMENT ON COLUMN AUDITORIA.AUD_HIST_ID      IS 'COLUNA REFERENTE AO REGISTRO DA LINHA ALTERADA NO HISTORICO';
COMMENT ON COLUMN AUDITORIA.AUD_COLUNA       IS 'COLUNA REFERENTE AO NOME DA COLUNA AUDITADA';
COMMENT ON COLUMN AUDITORIA.AUD_VALOR_ANTIGO IS 'COLUNA REFERENTE AO VALOR ANTIGO DA COLUNA AUDITADA';
COMMENT ON COLUMN AUDITORIA.AUD_VALOR_NOVO   IS 'COLUNA REFERENTE AO VALOR NOVO DA COLUNA AUDITADA';
COMMENT ON COLUMN AUDITORIA.AUD_DATA         IS 'COLUNA REFERENTE A DATA DA ALTERACAO';
COMMENT ON COLUMN AUDITORIA.AUD_USU_BD       IS 'COLUNA REFERENTE AO USUARIO DO BANCO RESPONSAVEL PELA ALTERACAO';
COMMENT ON COLUMN AUDITORIA.AUD_USU_SO       IS 'COLUNA REFERENTE AO USUARIO DO SISTEMA OPERACIONAL';
COMMENT ON COLUMN AUDITORIA.AUD_OPERACAO     IS 'COLUNA REFERENTE A OPERACAO REALIZADA';

/
COMMIT;
