-- PROCEDURE AUDITORIA
CREATE OR REPLACE PROCEDURE PROC_AUDITORIA (
    P_AUD_TABELA       IN VARCHAR2,
    P_AUD_HIST_ID      IN VARCHAR2,
    P_AUD_COLUNA       IN VARCHAR2,
    P_AUD_VALOR_ANTIGO IN VARCHAR2,
    P_AUD_VALOR_NOVO   IN VARCHAR2,
    P_AUD_DATA         IN TIMESTAMP,
    P_AUD_USU_BD       IN VARCHAR2,
    P_AUD_USU_SO       IN VARCHAR2,
    P_AUD_OPERACAO     IN CHAR
)
IS
BEGIN
    INSERT INTO AUDITORIA
    VALUES(
        NULL,
        P_AUD_TABELA,
        P_AUD_HIST_ID,
        P_AUD_COLUNA,
        P_AUD_VALOR_ANTIGO,
        P_AUD_VALOR_NOVO,
        P_AUD_DATA,
        P_AUD_USU_BD,
        P_AUD_USU_SO,
        P_AUD_OPERACAO
    );
END;
/
COMMIT;
