
-- TRIGGER AUDITORIA
CREATE TRIGGER TG_AUD
BEFORE INSERT ON AUDITORIA
FOR EACH ROW
BEGIN
    :NEW.AUD_ID := SQ_AUD.NEXTVAL;
END;
/

COMMIT;

-- TRIGGER HPRODUTO
CREATE OR REPLACE TRIGGER TG_AUD_HPRD
AFTER UPDATE OR DELETE ON ALFA.HPRODUTO
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HPRODUTO';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_ID',:OLD.HPRD_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_NOME',:OLD.HPRD_NOME,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_DATE',TO_CHAR(:OLD.HPRD_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HPRD_ID != :NEW.HPRD_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_ID',:OLD.HPRD_ID,:NEW.HPRD_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HPRD_NOME != :NEW.HPRD_NOME THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_NOME',:OLD.HPRD_NOME,:NEW.HPRD_NOME,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HPRD_DATE != :NEW.HPRD_DATE THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HPRD_ID,'HPRD_DATE',TO_CHAR(:OLD.HPRD_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HPRD_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

-- TRIGGER HCANAL
CREATE OR REPLACE TRIGGER TG_AUD_HCAN
AFTER UPDATE OR DELETE ON ALFA.HCANAL
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HCANAL';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_ID',:OLD.HCAN_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_NOME',:OLD.HCAN_NOME,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_DATE',TO_CHAR(:OLD.HCAN_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HCAN_ID != :NEW.HCAN_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_ID',:OLD.HCAN_ID,:NEW.HCAN_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HCAN_NOME != :NEW.HCAN_NOME THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_NOME',:OLD.HCAN_NOME,:NEW.HCAN_NOME,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HCAN_DATE != :NEW.HCAN_DATE THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HCAN_ID,'HCAN_DATE',TO_CHAR(:OLD.HCAN_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HCAN_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

-- TRIGGER HLOJA
CREATE OR REPLACE TRIGGER TG_AUD_HLOJ
AFTER UPDATE OR DELETE ON ALFA.HLOJA
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HLOJA';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_ID',:OLD.HLOJ_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_NOME',:OLD.HLOJ_NOME,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_DATE',TO_CHAR(:OLD.HLOJ_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HLOJ_ID != :NEW.HLOJ_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_ID',:OLD.HLOJ_ID,:NEW.HLOJ_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HLOJ_NOME != :NEW.HLOJ_NOME THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_NOME',:OLD.HLOJ_NOME,:NEW.HLOJ_NOME,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HLOJ_DATE != :NEW.HLOJ_DATE THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HLOJ_ID,'HLOJ_DATE',TO_CHAR(:OLD.HLOJ_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HLOJ_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

-- TRIGGER HSKU
CREATE OR REPLACE TRIGGER TG_AUD_HSKU
AFTER UPDATE OR DELETE ON ALFA.HSKU
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HSKU';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_ID',:OLD.HSKU_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_KEY',:OLD.HSKU_KEY,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_PRD_ID',:OLD.HSKU_PRD_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_CUSTO',:OLD.HSKU_CUSTO,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_DATE',TO_CHAR(:OLD.HSKU_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HSKU_ID != :NEW.HSKU_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_ID',:OLD.HSKU_ID,:NEW.HSKU_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HSKU_KEY != :NEW.HSKU_KEY THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_KEY',:OLD.HSKU_KEY,:NEW.HSKU_KEY,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HSKU_PRD_ID != :NEW.HSKU_PRD_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_PRD_ID',:OLD.HSKU_PRD_ID,:NEW.HSKU_PRD_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HSKU_CUSTO != :NEW.HSKU_CUSTO THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_CUSTO',:OLD.HSKU_CUSTO,:NEW.HSKU_CUSTO,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HSKU_DATE != :NEW.HSKU_DATE THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HSKU_ID,'HSKU_DATE',TO_CHAR(:OLD.HSKU_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HSKU_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

-- TRIGGER HVENDA
CREATE OR REPLACE TRIGGER TG_AUD_HVND
AFTER UPDATE OR DELETE ON ALFA.HVENDA
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HVENDA';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_ID',:OLD.HVND_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_PEDIDO',:OLD.HVND_PEDIDO,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_LOJ_ID',:OLD.HVND_LOJ_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_CAN_ID',:OLD.HVND_CAN_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_DATA_VENDA',TO_CHAR(:OLD.HVND_DATA_VENDA,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_VALOR_TOTAL',:OLD.HVND_VALOR_TOTAL,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_DATE',TO_CHAR(:OLD.HVND_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HVND_ID != :NEW.HVND_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_ID',:OLD.HVND_ID,:NEW.HVND_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_PEDIDO != :NEW.HVND_PEDIDO THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_PEDIDO',:OLD.HVND_PEDIDO,:NEW.HVND_PEDIDO,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_LOJ_ID != :NEW.HVND_LOJ_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_LOJ_ID',:OLD.HVND_LOJ_ID,:NEW.HVND_LOJ_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_CAN_ID != :NEW.HVND_CAN_ID THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_CAN_ID',:OLD.HVND_CAN_ID,:NEW.HVND_CAN_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_DATA_VENDA != :NEW.HVND_DATA_VENDA THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_DATA_VENDA',TO_CHAR(:OLD.HVND_DATA_VENDA,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HVND_DATA_VENDA,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_VALOR_TOTAL != :NEW.HVND_VALOR_TOTAL THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_VALOR_TOTAL',:OLD.HVND_VALOR_TOTAL,:NEW.HVND_VALOR_TOTAL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HVND_DATE != :NEW.HVND_DATE THEN
            PROC_AUDITORIA(V_TABELA,:OLD.HVND_ID,'HVND_DATE',TO_CHAR(:OLD.HVND_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HVND_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

-- TRIGGER HITEM_VENDA
CREATE OR REPLACE TRIGGER TG_AUD_HITVND
AFTER UPDATE OR DELETE ON ALFA.HITEM_VENDA
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_TABELA VARCHAR2(30) := 'HITEM_VENDA';
    V_HIST_ID VARCHAR2(100);
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_HIST_ID := :OLD.HITVND_VND_ID || '-' || :OLD.HITVND_SKU_ID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_VND_ID',:OLD.HITVND_VND_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_SKU_ID',:OLD.HITVND_SKU_ID,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_QTDE',:OLD.HITVND_QTDE,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_CUSTO',:OLD.HITVND_CUSTO,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_VALOR',:OLD.HITVND_VALOR,NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_DATE',TO_CHAR(:OLD.HITVND_DATE,'YYYY-MM-DD HH24:MI:SS'),NULL,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
    ELSE
        V_TP_OPERACAO := 'U';
        IF :OLD.HITVND_VND_ID != :NEW.HITVND_VND_ID THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_VND_ID',:OLD.HITVND_VND_ID,:NEW.HITVND_VND_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HITVND_SKU_ID != :NEW.HITVND_SKU_ID THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_SKU_ID',:OLD.HITVND_SKU_ID,:NEW.HITVND_SKU_ID,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HITVND_QTDE != :NEW.HITVND_QTDE THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_QTDE',:OLD.HITVND_QTDE,:NEW.HITVND_QTDE,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HITVND_CUSTO != :NEW.HITVND_CUSTO THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_CUSTO',:OLD.HITVND_CUSTO,:NEW.HITVND_CUSTO,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HITVND_VALOR != :NEW.HITVND_VALOR THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_VALOR',:OLD.HITVND_VALOR,:NEW.HITVND_VALOR,SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
        IF :OLD.HITVND_DATE != :NEW.HITVND_DATE THEN
            PROC_AUDITORIA(V_TABELA,V_HIST_ID,'HITVND_DATE',TO_CHAR(:OLD.HITVND_DATE,'YYYY-MM-DD HH24:MI:SS'),TO_CHAR(:NEW.HITVND_DATE,'YYYY-MM-DD HH24:MI:SS'),SYSDATE,V_USU_BD,V_USU_SO,V_TP_OPERACAO);
        END IF;
    END IF;
END;
/

COMMIT;